//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfforex
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Categorie { get; set; }
        public Nullable<int> id_Cart { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Categories Categories { get; set; }

        public double? Sum
        {
            get
            {
                return Cost * Count;
            }
        }



        
    }
}
